<?php

return [
    'static' => [
        'contact-us' => 'includes/contact-us.php',
        'help-center' => 'includes/help-center.php',
        'how-to-deposit' => 'includes/how-to-deposit.php',
        'how-to-withdraw' => 'includes/how-to-withdraw.php',
        'how-to-open-account' => 'includes/how-to-open-account.php',
        'how-to-verify-account' => 'includes/how-to-verify-account.php',
        'how-copy-trading-works' => 'includes/how-copy-trading-works.php',
        'invite-a-friend' => 'includes/invite-a-friend.php',
        'ib-program' => 'includes/ib-program.php',
        'courses' => 'includes/courses.php',
        'trading-essentials' => 'includes/trading-essentials.php',
        'video-education' => 'includes/video-education.php',
        'research' => 'includes/research.php',
        'live-training' => 'includes/live-training.php',
        'offers' => 'includes/offers.php',
        'offers-promotions' => 'includes/offers.php',
        'vn' => 'includes/offers.php',
        'th' => 'includes/offers.php',
        'ph' => 'includes/offers.php',
        'id' => 'includes/offers.php',
        'pk' => 'includes/offers.php',
        'latam' => 'includes/offers.php',
        'na' => 'includes/offers.php',
        'ke' => 'includes/offers.php',
        'gh' => 'includes/offers.php',
        'ng' => 'includes/offers.php',
        'za' => 'includes/offers.php',
        'tt' => 'includes/offers.php',
        'gy' => 'includes/offers.php',
        'trading-platform' => 'includes/trading-platform.php',
        'trading-central' => 'includes/trading-central.php',
        'legal-documents' => 'includes/legal-documents.php',
        'regulations' => 'includes/regulations.php',
        'events-calendar' => 'includes/events-calendar.php',
        'education-hub' => 'includes/education-hub.php',
        'education-article' => 'includes/education-article.php',
        'forex-trading-fundamentals' => 'includes/edu-hub/forex-trading-fundamentals.php',
        'cfd-trading-basics' => 'includes/edu-hub/cfd-trading-basics.php',
        'leverage-margin-risk-basics' => 'includes/edu-hub/leverage-margin-risk-basics.php',
        'risk-management-essentials' => 'includes/edu-hub/risk-management-essentials.php',
        'technical-analysis-for-beginners' => 'includes/edu-hub/technical-analysis-for-beginners.php',
        'fundamental-analysis-basics' => 'includes/edu-hub/fundamental-analysis-basics.php',
        'trading-psychology-basics' => 'includes/edu-hub/trading-psychology-basics.php',
        'gold-trading-for-beginners' => 'includes/edu-hub/gold-trading-for-beginners.php',
        'indices-trading-basics' => 'includes/edu-hub/indices-trading-basics.php',
        'platform-basics' => 'includes/edu-hub/platform-basics.php',
        'meet-the-team' => 'includes/meet-the-team.php',
        'account-types' => 'includes/account-types.php',
        'privacy-policy' => 'includes/privacy-policy.php',
        'client-vulnerability' => 'includes/client-vulnerability.php',
        'responsible-trading' => 'includes/responsible-trading.php',
        'interest-on-balance' => 'includes/interest-on-balance.php',
        'buy-and-sell-explained' => 'includes/buy-and-sell-explained.php',
        'tax-report' => 'includes/tax-report.php',
        'what-is-leverage-and-margin' => 'includes/what-is-leverage-and-margin.php',
        'accessibility' => 'includes/accessibility.php',
        'key-information-documents' => 'includes/key-information-documents.php',
        'terms-conditions' => 'includes/terms-conditions.php',
        'anti-money-laundering-policy' => 'includes/anti-money-laundering-policy.php',
        'order-execution-policy' => 'includes/order-execution-policy.php',
        'risk-disclosure' => 'includes/risk-disclosure.php',
        'general-risk-disclosure' => 'includes/general-risk-disclosure.php',
        'client-service-agreement' => 'includes/client-service-agreement.php',
        'cookie-policy' => 'includes/cookies-policy.php',
        'cookies-policy' => 'includes/cookies-policy.php',
        'edu-market-news' => 'includes/edu-market-news.php',
        'edu-ebooks' => 'includes/edu-ebooks.php',
        'edu-webinars' => 'includes/edu-webinars.php',
        'edu-glossary' => 'includes/edu-glossary.php',
        'edu-tutorials' => 'includes/edu-tutorials.php',
        'edu-resources' => 'includes/edu-resources.php',
        'open-demo-account' => 'includes/open-demo-account.php',
        'open-live-account' => 'includes/open-live-account.php',
        'lead-thank-you' => 'includes/lead-thank-you.php',
        'about' => 'includes/about.php',
        'blog' => 'includes/blog.php',
        'reviews' => 'includes/reviews.php',
        'segregated-account' => 'includes/segregated-account.php',
        'top-instruments' => 'includes/top-instruments.php',
        'tradertok-club' => 'includes/tradertok-club.php',
    ],
    'dynamic' => [
        'otherPage',
        'extraMenu',
        'documents',
        'blogDetail',
    ],
];
